name: PCDS Standard Testing

on:
  push:
  pull_request:
  release:
    types:
      - created

jobs:
  standard:
    uses: tangkong/pcds-ci-helpers/.github/workflows/python-standard.yml@mnt_rm_perms
    secrets: inherit
    with:
      # The workflow needs to know the package name.  This can be determined
      # automatically if the repository name is the same as the import name.
      package-name: "typhos"
      # Extras that will be installed for both conda/pip:
      testing-extras: "happi"
      # Extras to be installed only for conda-based testing:
      conda-testing-extras: ""
      # Extras to be installed only for pip-based testing:
      pip-testing-extras: ""
      # Set if using setuptools-scm for the conda-build workflow
      use-setuptools-scm: true
